import { Request, Response } from "express";
import { extractTextFromInput } from "../utils/extractText";
import axios from "axios";
interface FileRequest extends Request {
  file?: Express.Multer.File;
}

export async function summarizeText(req:FileRequest,res:Response) {
    try{
        const text=await extractTextFromInput({
            text:req.body.text,
            fileBuffer:req.file?.buffer,
        })
        const HF_apiKey=process.env.HUGGINGFACE_API_KEY
        if (!HF_apiKey) {
            return res.status(500).json({ message: "Missing HuggingFace API Key" });
        }

        const model='sshleifer/distilbart-cnn-12-6'
        const response=await axios.post(`https://api-inference.huggingface.co/models/${model}`,
                {inputs:text},
                {headers:{ Authorization: `Bearer ${HF_apiKey}`,"Content-Type": "application/json",}},)
        const summary = response.data[0]?.summary_text
        if (!summary) {
            res.status(502).json({ message: "No summary generated by model" });
            return
        }
        res.json({summary})
    }    
    catch(error){
        console.error("Summarization error:", error);
        res.status(500).json({ message: "Error summarizing blog" });
    }
}